[package]
name = "schach"
version = "0.1.0"
edition = "2024"

[dependencies]
mattr = "1.0.1"
owlchess = "0.4.0"
paste = "1.0.15"
rayon = "1.11.0"
strum = { version = "0.27.2", features = ["derive"] }
