[package]
name = "schach"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.2", optional = true }

[dev-dependencies]
owlchess = "0.4.0"

[features]
std = []
rand = ["dep:rand"]
